version: '3.7'

services:
  eed-api:
    image: ghcr.io/solsystemlabs/eed-api:latest
    volumes:
      - ./src:/home/node/app/src
      - eed-api-secrets:/home/node/app
    expose:
      - '4000'
    ports:
      - '4000:3000'
    command: 'npm run dev'

volumes:
  eed-api-secrets:
    external: true