version: '3.7'

services:
  eed-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/home/node/app/src
    container_name: eed-api
    expose:
      - '4000'
    ports:
      - '4000:3000'
    command: npm run dev
