name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/solsystemlabs/eed-api:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      # - name: Docker over SSH
      #   # You may pin to the exact commit or the version.
      #   # uses: pcjun97/action-setup-docker-host-ssh@66b37629da941d78f37d8ede50ea50b841b8e8be
      #   uses: pcjun97/action-setup-docker-host-ssh@v1
      #   with:
      #     # Remote Docker host
      #     host: ${{ secrets.PORTAINER_HOST }}
      #     # SSH user
      #     user: ${{ secrets.PORTAINER_USER }}
      #     # Content of SSH private key
      #     key: ${{ secrets.DEPLOY_TOKEN }}
      #     key_path: ${{ secrets.KEY_PATH }}
      
      # - name: Write SSH keys
      #   run: |
      #     install -m 600 -D /dev/null ~/.ssh/id_rsa
      #     echo "${{ secrets.RUNNER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     host='${{ secrets.PORTAINER_HOST }}'
      #     hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
      #     ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      # - name: Docker Compose Action
      #   uses: hoverkraft-tech/compose-action@v2.0.0

      - name: SSH Remote Commands
        # You may pin to the exact commit or the version.
        # uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
        uses: appleboy/ssh-action@v1.0.3
        with:
          # SSH host address.
          host: ${{ secrets.PORTAINER_HOST }}
          # SSH username.
          username: ${{ secrets.PORTAINER_USER }}
          # Content of the SSH private key. For example, the raw content of ~/.ssh/id_rsa.
          key: ${{ secrets.RUNNER_PRIVATE_KEY }}
          script: "echo 'hello'"
          
          
                
