name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/solsystemlabs/eed-api:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Docker over SSH
      #   # You may pin to the exact commit or the version.
      #   # uses: pcjun97/action-setup-docker-host-ssh@66b37629da941d78f37d8ede50ea50b841b8e8be
      #   uses: pcjun97/action-setup-docker-host-ssh@v1
      #   with:
      #     # Remote Docker host
      #     host: ${{ secrets.PORTAINER_HOST }}
      #     # SSH user
      #     user: ${{ secrets.PORTAINER_USER }}
      #     # Content of SSH private key
      #     key: ${{ secrets.DEPLOY_TOKEN }}
      #     key_path: ${{ secrets.KEY_PATH }}

      - name: Docker Compose Remote Deploy
        uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_key: ${{ secrets.RUNNER_PRIVATE_KEY }}
          ssh_user: ${{ secrets.PORTAINER_USER }}
          ssh_host: ${{ secrets.PORTAINER_HOST }}
          compose_file: docker-compose.yaml
            
        
                
                
                      
                            
