name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
    build:
      runs-on: self-hosted

      steps:
        - name: Checkout Code
          uses: actions/checkout@v4.1.2
          
        - name: 'Create env file'
          run: |
            touch $GITHUB_WORKSPACE/.env
            echo "${{ secrets.ENV_FILE }}" > $GITHUB_WORKSPACE/.env
            
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3.1.0
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ghcr.io/${{github.repository_owner}}/eed-api
            tags: |
              type=ref,event=branch
              type=raw,value=latest,enable={{is_default_branch}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5.3.0
          with:
            context: .
            push: true
            secret-files: .env
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

    deploy:
      needs: build
      runs-on: self-hosted
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.2
        - uses: chaplyk/docker-compose-remote-action@v1.1
          name: Docker Compose Remote Action
          with:
            ssh_host: ${{ secrets.PORTAINER_HOST }}
            ssh_user: ${{ secrets.GH_USER_NAME }}
            ssh_key: ${{ secrets.RUNNER_PRIVATE_KEY }}
            compose_file: docker-compose.yaml
            pull: true
            force_recreate: true
